---
title: "Column-wise operations: Your Turn"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(palmerpenguins)
```


## Your Turn #1

Take a look at the following code chunk:

```{r question-1-code, eval=FALSE, echo=TRUE}
penguins %>% 
  summarize(bill_length_mm = mean(bill_length_mm, na.rm = TRUE),
            bill_depth_mm = mean(bill_depth_mm, na.rm = TRUE))
```


```{r question-1}
question("Which of the following is equivalent to the code chunk shown above?",
  # wrong
  answer("`penguins %>% 
  summarize_if(vars(c(bill_length_mm, bill_depth_mm)), mean, na.rm = TRUE)`", 
  message = "Try again! The scoped verb you're looking for is `summarize_at()`"),
  # wrong
  answer("`penguins %>% 
  summarize_at(vars(c(bill_length_mm, bill_depth_mm)), mean)`",
  message = "Not quite. Don't forget about additional arguments to `mean()` that must be passed through with `...`"),
  # correct
  answer("`penguins %>% 
  summarize_at(vars(c(starts_with('bill'))), mean, na.rm = TRUE)`", correct = TRUE),
  message = "Nice work! You can use select helpers like `starts_with()` or `contains()` when selecting columns",
  # wrong
  answer("`penguins %>% 
  summarize_at(c(bill_length_mm, bill_depth_mm), mean, na.rm = TRUE)`",
  message = "Not quite. Remember that the columns selected in `summarize_at()` must be wrapped inside `vars()`")
)
```

## Your Turn # 2

For each island, find the maximum value of all body dimensions (including body mass).  

```{r}
penguins %>% 
  group_by(island) %>% 
  summarize(across(c(where(is.numeric), -year), max, na.rm = TRUE, .names = "{col}_max"))
```


